<!--#include File="Conn.asp" -->
<!--#include file="Checkpost.asp"-->
<!--#include file="888wang_chkAdmin.asp"-->
<%CheckAdmin3%>
<%

Response.Write "<Html>"
Response.Write "<Head>"
Response.Write "<Title>管理中心 - "& WebName &"</title>"
Response.Write "<Meta Http-Equiv=""Content-Type"" Content=""Text/Html; CharSet=Gb2312"">"
Response.Write "<Link Type=""Text/Css"" Rel=""StyleSheet"" Href=""Inc/Style.css"">"
Response.Write "</Head>"
Response.Write "<Body bgcolor=""#7B9AE7""><br>"
Response.Write "<div align=""center"">"
Response.Write "<center>"
Response.Write "<table border=""0"" cellpadding=""0"" cellspacing=""0"" width=""95%"">"
Response.Write "<tr>"
Response.Write "<td width=""100%"" bgcolor=""#FFFFFF"">"
Response.Write "<div align=""center"">"
Response.Write "<table border=""0"" cellpadding=""0"" cellspacing=""14"" width=""100%"">"
Response.Write "<tr>"
Response.Write "<td width=""100%""><font size=""2""><br>"
Response.Write "</font>"
Response.Write "<p align=""center""><b>"& WebName &"</b></p>"
Response.Write "<b>操作说明</b>：<br>"
Response.Write "<br>1. 添加FLASH &gt; 可通过Web添加FLASH，请选择添加FLASH项。</font>"
Response.Write "<p><font size=""2"">2. FLASH管理 &gt; 可对已经添加的FLASH进行修改，删除，生成Html页面。</font></p>"
Response.Write "<p><font size=""2"">3. 类别管理 &gt; 可对FLASH类别进行修改，删除，添加，生成Html页面。</font></p>"
Response.Write "<p><font size=""2"">4. 生成首页 &gt; 可对首页进行生成Html页面，更新。</font></p>"
Response.Write "<p><font size=""2"">5. 修改模版 &gt; 可对页面模版，分类模版进行修改。</font></p>"
Response.Write "<p><font size=""2"">6. <font color=""red"">为了系统的安全性，离开管理请点击退出管理。</font></font></p>"
Response.Write "<p><font size=""2"">在线QQ联系：56566918</font> [888网]，3年专业娱乐程序开发，让你建站飞一样的快!</p>提示：为保障你的权益，请到官方网站www.888wang.com购买程序及数据!<p>"
Response.Write "<p align=""center""><font size=""2"">888网小游戏- 版权所有 Copyright"
Response.Write "&copy; 2004-2008 www.888wang.com All Rights Reserved</font></td>"
Response.Write "</tr>"
Response.Write "</table>"
Response.Write "</div>"
Response.Write "</td>"
Response.Write "</tr>"
Response.Write "</table>"
Response.Write "</center>"
Response.Write "</div>"
Response.Write "</body>"
Response.Write "</html>"
%>

