document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"ca-pub-0996510625872678\";");
document.writeln("\/* 160x600, ´´½¨ÓÚ 11-4-29 *\/");
document.writeln("google_ad_slot = \"4617215869\";");
document.writeln("google_ad_width = 160;");
document.writeln("google_ad_height = 600;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");