document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln("#play_top {");
document.writeln("	text-align: center;");
document.writeln("}");
document.writeln("#play_top img {");
document.writeln("	padding: 1px;");
document.writeln("	border: 2px solid #9CD6FE;");
document.writeln("}");
document.writeln("#play_top img:hover {");
document.writeln("	border: 2px solid #FF0000;");
document.writeln("}");
document.writeln("body {");
document.writeln("	margin: 0px;");
document.writeln("}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<table width=\"940\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"play_top\">");
document.writeln("  <tr>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/91334\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Toilet2.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/61329\/\" target=\"_blank\"><img src=\"\/images\/play_top\/war2.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/71328\/\" target=\"_blank\"><img src=\"\/images\/play_top\/2084.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/e1298\/\" target=\"_blank\"><img src=\"\/images\/play_top\/tear5.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/41300\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Summoning.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/41306\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Pancakeria.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/41335\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Decision.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<div style=\"height:6px\"><\/div>");
document.writeln("<table width=\"940\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"play_top\">");
document.writeln("  <tr>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/51325\/\" target=\"_blank\"><img src=\"\/images\/play_top\/hanger2l.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/c1322\/\" target=\"_blank\"><img src=\"\/images\/play_top\/crash.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/51357\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Selena.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/41362\/\" target=\"_blank\"><img src=\"\/images\/play_top\/egg.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/91372\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Couple.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/01374\/\" target=\"_blank\"><img src=\"\/images\/play_top\/tank2012.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td><a href=\"http:\/\/www.acool.com\/playInfo\/31376\/\" target=\"_blank\"><img src=\"\/images\/play_top\/Beach.jpg\" width=\"120\" height=\"120\" border=\"0\" \/><\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("");