document.writeln("<style>");
document.writeln("\/*index_tag_s*\/");
document.writeln(".tag {");
document.writeln("	height: 210px;");
document.writeln("	width: 980px;");
document.writeln("	margin-right: 10px;");
document.writeln("	margin-left: 10px;");
document.writeln("	background-image: url(\/images\/tag_bg.jpg);");
document.writeln("	background-repeat: no-repeat;");
document.writeln("	background-position: left top;");
document.writeln("	padding-top: 20px;");
document.writeln("}");
document.writeln(".tagall {");
document.writeln("	width: 89px;");
document.writeln("	float: left;");
document.writeln("	text-align: center;");
document.writeln("	margin-top: 10px;");
document.writeln("}");
document.writeln(".tagall a{");
document.writeln("	font-size: 12px;");
document.writeln("	text-decoration: none;");
document.writeln("	font-weight: bold;");
document.writeln("	line-height: 17px;");
document.writeln("	color: #666666;");
document.writeln("	font-family: Arial;");
document.writeln("}");
document.writeln(".tagall a:hover{");
document.writeln("	text-decoration: none;");
document.writeln("	color: #FF3300;");
document.writeln("}");
document.writeln("\/*index_tag_e*\/");
document.writeln("<\/style>");
document.writeln("");
document.writeln("<div class=\"tag\">");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/Angry-1.html\" ><img src=\"\/images\/2014tag\/birds.png\" border=\"0\" \/><br>");
document.writeln("  AngryBirds<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/gangnam-1.html\" ><img src=\"\/images\/2014tag\/psy.png\" border=\"0\" \/><br>");
document.writeln("  Gangnam<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/zombie-1.html\" ><img src=\"\/images\/2014tag\/Zombie.png\" border=\"0\" \/><br>");
document.writeln("  Zombie<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/beauty-1.html\" ><img src=\"\/images\/2014tag\/Beauty.png\" border=\"0\" \/><br>");
document.writeln("  Beauty<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/minion-1.html\" ><img src=\"\/images\/2014tag\/minion.png\" border=\"0\" \/><br>");
document.writeln("  Minions<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/mario-1.html\" ><img src=\"\/images\/2014tag\/mario.png\" border=\"0\" \/><br>");
document.writeln("  Mario<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/ben10-1.html\" ><img src=\"\/images\/2014tag\/ben10.png\" border=\"0\" \/><br>");
document.writeln("  Ben10<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/PowerRangers-1.html\" ><img src=\"\/images\/2014tag\/power.png\" border=\"0\" \/><br>");
document.writeln("  PowerRangers<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/Tom&Jerry-1.html\" ><img src=\"\/images\/2014tag\/tom.png\" border=\"0\" \/><br>");
document.writeln("  Tom&Jerry<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/ninja-1.html\" ><img src=\"\/images\/2014tag\/ninja.png\" border=\"0\" \/><br>");
document.writeln("  Ninja<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"http:\/\/m.acool.com\" ><img src=\"\/images\/2014tag\/mobile.png\" border=\"0\" \/><br>");
document.writeln("  Mobile Games<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/lego-1.html\" ><img src=\"\/images\/2014tag\/lego.png\" border=\"0\" \/><br>");
document.writeln("  LEGO<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/PhineasAndFerb-1.html\" ><img src=\"\/images\/2014tag\/PhineasAndFerb.png\" border=\"0\" \/><br>");
document.writeln("  Phineas&Ferb<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/disney-1.html\" ><img src=\"\/images\/2014tag\/Disney.png\" border=\"0\" \/><br>");
document.writeln("  Disney<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/AdventureTime-1.html\" ><img src=\"\/images\/2014tag\/AdventureTime.png\" border=\"0\" \/><br>");
document.writeln("  AdventureTime<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/talking-1.html\" ><img src=\"\/images\/2014tag\/talking.png\" border=\"0\" \/><br>");
document.writeln("  Talking Tom<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/pou-1.html\" ><img src=\"\/images\/2014tag\/Pou.png\" border=\"0\" \/><br>");
document.writeln("  Pou<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/stickman-1.html\" ><img src=\"\/images\/2014tag\/stickman.png\" border=\"0\" \/><br>");
document.writeln("  Stickman<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/DragonBall-1.html\" ><img src=\"\/images\/2014tag\/db.png\" border=\"0\" \/><br>");
document.writeln("  DragonBall<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/cartoon-1.html\" ><img src=\"\/images\/2014tag\/cn.png\" border=\"0\" \/><br>");
document.writeln("  Cartoon<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/tag\/Robot-1.html\" ><img src=\"\/images\/2014tag\/robot.png\" border=\"0\" \/><br>");
document.writeln("  Robot<\/a><\/div>");
document.writeln("<div class=\"tagall\"><a href=\"\/game\/fun-1.html\" ><img src=\"\/images\/2014tag\/fun.png\" border=\"0\" \/><br>");
document.writeln("  Fun Games<\/a><\/div>");
document.writeln("<\/div>");