document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".tag {");
document.writeln("	height: 100px;");
document.writeln("	width: 960px;");
document.writeln("	border: 1px solid #999999;");
document.writeln("	background-color: #000000;");
document.writeln("	margin-right: auto;");
document.writeln("	margin-left: auto;");
document.writeln("	float: left;");
document.writeln("	margin-top: 9px;");
document.writeln("}");
document.writeln(".tagall {");
document.writeln("	height: 100px;");
document.writeln("	width: 87px;");
document.writeln("	float: left;");
document.writeln("}");
document.writeln(".tagimg {");
document.writeln("	height: 65px;");
document.writeln("	width: 87px;");
document.writeln("	text-align: center;");
document.writeln("	margin-top: 10px;");
document.writeln("}");
document.writeln(".tagtext {");
document.writeln("	width: 87px;");
document.writeln("	text-align: center;");
document.writeln("	line-height: 25px;");
document.writeln("}");
document.writeln(".tagtext a{");
document.writeln("	font-size: 12px;");
document.writeln("	text-decoration: none;");
document.writeln("	color: #00CCFF;");
document.writeln("}");
document.writeln(".tagtext a:hover{");
document.writeln("	font-size: 12px;");
document.writeln("	text-decoration: underline;");
document.writeln("	color: #FF3300;");
document.writeln("}");
document.writeln("body {");
document.writeln("	margin: 0px;");
document.writeln("}");
document.writeln("");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<!--Tag-icon-S-->");
document.writeln("<div class=\"tag\">");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/339_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/3.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/339_1\/\" >Mario<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/c43_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/4.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/c43_1\/\" >Ben 10<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/548_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/ninja.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/548_1\/\" >Ninja<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/e71_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/disney.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/e71_1\/\" >Disney<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/053_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/Superhero.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/053_1\/\" >Superhero<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/game\/548_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/kissing.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/game\/548_1\/\" >Kissing<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/game\/550_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/baby.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/game\/550_1\/\" >Baby<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/662_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/simpson.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/662_1\/\" >Simpson<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/672_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/cartoon.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/672_1\/\" >Cartoon<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/d54_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/Transformers.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/d54_1\/\" >Transformers<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/441_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/9.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/441_1\/\" >Beauty<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("<\/div>");
document.writeln("<div style=\"clear:both;\"><\/div>");
document.writeln("<!--Tag-icon-E-->");