document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".tag {");
document.writeln("	height: 100px;");
document.writeln("	width: 960px;");
document.writeln("	border: 1px solid #999999;");
document.writeln("	background-color: #000000;");
document.writeln("	margin-right: auto;");
document.writeln("	margin-left: auto;");
document.writeln("	float: left;");
document.writeln("	margin-top: 9px;");
document.writeln("}");
document.writeln(".tagall {");
document.writeln("	height: 100px;");
document.writeln("	width: 87px;");
document.writeln("	float: left;");
document.writeln("}");
document.writeln(".tagimg {");
document.writeln("	height: 65px;");
document.writeln("	width: 87px;");
document.writeln("	text-align: center;");
document.writeln("	margin-top: 10px;");
document.writeln("}");
document.writeln(".tagtext {");
document.writeln("	width: 87px;");
document.writeln("	text-align: center;");
document.writeln("	line-height: 25px;");
document.writeln("}");
document.writeln(".tagtext a{");
document.writeln("	font-size: 12px;");
document.writeln("	text-decoration: none;");
document.writeln("	color: #00CCFF;");
document.writeln("}");
document.writeln(".tagtext a:hover{");
document.writeln("	font-size: 12px;");
document.writeln("	text-decoration: underline;");
document.writeln("	color: #FF3300;");
document.writeln("}");
document.writeln("body {");
document.writeln("	margin: 0px;");
document.writeln("}");
document.writeln("");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<!--Tag-icon-S-->");
document.writeln("<div class=\"tag\">");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/438_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/2.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/438_1\/\" >Angry Birds<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/537_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/1.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/537_1\/\" >Gangnam<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/069_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/lego.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/069_1\/\" >LEGO<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/c44_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/7.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/c44_1\/\" >Spongebob<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/574_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/PhineasAndFerb.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/574_1\/\" >PhineasAndFerb<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/d46_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/5.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/d46_1\/\" >Zombie<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/551_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/power.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/551_1\/\" >PowerRangers<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/140_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/6.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/140_1\/\" >Dora<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/f63_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/AdventureTime.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/f63_1\/\" >AdventureTime<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/tag\/852_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/tom.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/tag\/852_1\/\" >Tom&Jerry<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("<div class=\"tagall\">");
document.writeln("  <div class=\"tagimg\"><a href=\"http:\/\/www.acool.com\/game\/053_1\/\" ><img src=\"http:\/\/www.acool.com\/images\/tag\/fun.jpg\" border=\"0\" \/><\/a><\/div>");
document.writeln("  <div class=\"tagtext\"><a href=\"http:\/\/www.acool.com\/game\/053_1\/\" >Fun Games<\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("<\/div>");
document.writeln("<div style=\"clear:both;\"><\/div>");
document.writeln("<!--Tag-icon-E-->");