document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".mobile {");
document.writeln("}");
document.writeln(".mobile a {");
document.writeln("	display: block;");
document.writeln("	height: 56px;");
document.writeln("	width: 182px;");
document.writeln("	background-image: url(\/images\/mobilegames1.png);");
document.writeln("	background-repeat: no-repeat;");
document.writeln("	background-position: center top;");
document.writeln("}");
document.writeln(".mobile a:hover{");
document.writeln("	background-image: url(\/images\/mobilegames2.png);");
document.writeln("	background-repeat: no-repeat;");
document.writeln("	background-position: center top;");
document.writeln("}");
document.writeln("body {");
document.writeln("	margin: 0px;");
document.writeln("}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<div class=\"mobile\"><a href=\"http:\/\/m.acool.com\" target=\"_blank\"><\/a><\/div>");
document.writeln("");