document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"ca-pub-0996510625872678\";");
document.writeln("\/* 728x90, ´´½¨ÓÚ 10-12-30 *\/");
document.writeln("google_ad_slot = \"7050421794\";");
document.writeln("google_ad_width = 728;");
document.writeln("google_ad_height = 90;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");